### ISSUE TITLE
Some packages not exposed

### ISSUE THREAD

**Issue by TheMcMurder** [esm-bundle/rxjs#81]
[RxJS has multiple packages](https://rxjs.dev/api?type=package)

- operators
- ajax
- fetch
- websocket
- testing
- index

Currently we account for 2 of the above 6: `operators`, `index` but ignore `ajax`, `fetch`, `websocket`, `testing`.

This becomes a problem when using SystemJS and webpack externals marked as /^rxjs\/?.*$/,

If I make the external more specific then I run into the issue with finalize (#1) not working on all operators using any of the 4 ignored packages because I end up having two different builds of RxJS.

**Comment by joeldenning** [comment]
I was unaware of those other packages - let's support them. Do you have interest in helping add support? If not I may be able to do it sometime this week.
